### ISSUE TITLE
Format bug ?

### ISSUE THREAD

**Issue by vlamai** [NerdyPepper/eva#13]
If change format to this 
`let ans_string = format!("{:.*}", CONFIGURATION.fix, ans);`
My output look like 
![Screenshot_2019-04-02_17-49-32](https://user-images.githubusercontent.com/6729388/55403708-de405680-556f-11e9-958d-eb32bcb10b39.png)

**Comment by oppiliappan** [comment]
This is because fix is set to 10 if not provided as a flag!
