### ISSUE TITLE
history.txt file is written to current directory

### ISSUE THREAD

**Issue by wezm** [NerdyPepper/eva#16]
Whenever eva is run it writes a `history.txt` into the current directory. This results in a lot of these files lying around my system. I would prefer if eva used a central history file stored in the appropriate place on the given operating system (The [directories crate](https://crates.io/crates/directories) can help with that).

**Comment by oppiliappan** [comment]
I have used the `dirs` crate, and now history is stored in the home directory. back when `rustyline` was in version 3.x, it was not possible to save to a path!

if you have any suggestions regarding the location for the history file, let me know!

thank you for your contributions.

**Comment by wezm** [comment]
Great, thanks for the quick fix!

> if you have any suggestions regarding the location for the history file, let me know!

I don't think the home directory is the right place for the history. Reading the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) I would suggest using `XDG_DATA_HOME`, which corresponds to [data_dir](https://docs.rs/directories/2.0.1/directories/struct.ProjectDirs.html#method.data_dir) in `directories`.

**Comment by oppiliappan** [comment]
TIL about data home. i will make the suggested changes when I get back home!

**Comment by oppiliappan** [comment]
done! i havent tested too much, but it seems to be working fine!

**Comment by wezm** [comment]
Seems to work great!
