### ISSUE TITLE
When exiting with Ctrl-d eva prints CTRL-D

### ISSUE THREAD

**Issue by wezm** [NerdyPepper/eva#17]
**OS:** Linux

When exiting with <kbd>Ctr</kbd>+<kbd>d</kbd> `eva` prints `CTRL-D`. I would suggest that it's more conventional to just exit quietly.

**Comment by oppiliappan** [comment]
i noticed a couple of other programs that quietly quit on eof. i will adopt this style. changes will arrive with the next commit!
