### ISSUE TITLE
Exit Status Code for failure

### ISSUE THREAD

**Issue by KSXGitHub** [NerdyPepper/eva#2]
```sh
eva '3 / 0' 2> /dev/null
echo status $?
```

**expect:** 1

**received:** 0

**Comment by ngklingler** [comment]
Should it exit with code 1 though? Many applications don't fail on division by zero, they just flag it as undefined. pandas and SQL are two notable examples of this.

**Comment by oppiliappan** [comment]
im still not too sure about what to do. perhaps returning the exit status code when an error is encountered would help in scripts?

for now i shall implement what @KSXGitHub suggested.
