### ISSUE TITLE
Factorials

### ISSUE THREAD

**Issue by federico22598** [NerdyPepper/eva#22]
Whenever I try to calculate the factorial of a number greater than 63 (and less than 66, else it returns 0.0) I get the following error:
```
thread 'main' panicked at 'index out of bounds: the len is 36 but the index is 9223372036854775808', /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\slice\mod.rs:2686:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by oppiliappan** [comment]
thats weird i get a different error, which says `multiply with overflow` or something. ill switch over to the safe factorial crate to fix this, when i get some time.

**Comment by dtolnay** [comment]
Looks like an integer overflow; the output is off for smaller numbers too. As of the current master branch:

```console
$ cargo run --release -- 21!
14,197,454,024,290,336,768.0
```

The correct output would be 51,090,942,171,709,440,000.

**Comment by pickfire** [comment]
@NerdyPepper is anyone taking up this issue?

**Comment by oppiliappan** [comment]
@pickfire nope, i haven't really had the time and motivation to work on this.

feel free to take it up!

**Comment by pickfire** [comment]
I tried a simple check on it, the numbers are indeed wrong but I don't know what went wrong, maybe because of our use on `f64`? Or should we use `u32` instead?

```rust
fn factorial(n: f64) -> f64 {
    n.signum() * (1..=n.abs() as u64).fold(1, |p, n| p * n) as f64
}
```

It's sad to see factorial is not as easy to do with `u32` iterator example in the standard library.

```rust
fn factorial(n: u32) -> u32 {
    (1..=n).product()
}

**Comment by oppiliappan** [comment]
Yep, the issue arises from the last conversion `as f64`, unfortunately, a `Function` token has to have the signature `fn(f64) -> f64` right now, otherwise we would be able to return a `u32`.

A good start would be updating that signature to return a trait object of type `Num` from the [`num_traits`](https://docs.rs/num-traits/0.2.8/num_traits/trait.Num.html) crate.

**Comment by pickfire** [comment]
Okay, I don't think I will be helping out with this, not much motivation to use `21!` and higher. :P

Hopefully someone else can help out. @NerdyPepper Maybe you might want to label it `help-wanted` or something like that?

**Comment by oppiliappan** [comment]
I understand, :D

> Maybe you might want to label it help-wanted

Certainly, thanks for the suggestion!

**Comment by pickfire** [comment]
I was curious and went trying.
```
error[E0038]: the trait `format::num::Num` cannot be made into an object
  --> src/lex/mod.rs:47:26
   |
47 |     relation: fn(f64) -> dyn Num,
   |                          ^^^^^^^ the trait `format::num::Num` cannot be made into an object
   |
   = note: the trait cannot use `Self` as a type parameter in the supertraits or where-clauses

error: aborting due to previous error

For more information about this error, try `rustc --explain E0038`.
error: could not compile `eva`.
```
Looks like it does not work just like that, I also tried using `Box` but it does not work either.

**Comment by oppiliappan** [comment]
@pickfire  we would need something like this: 
```rust

struct Function<T: Num> {
    token: String,
    relation: fn(T) -> (T)
}
```

**Comment by Dev380** [comment]
Partially fixed with https://github.com/nerdypepper/eva/pull/53, turns out the conversion to `u64` and back to `f64` is causing the issue because of the relatively low max value of `u64` compared to `f64`, so just convert back to `f64` before multiplication. However, the precision issue is still not fixed and obviously needs separate logic for arbitrary precision.

**Comment by pickfire** [comment]
I change it to use `u128` when calculating factorial, that won't solve all the issues but at least `21!` can be calculated now.
