### ISSUE TITLE
Add support for Python-like catching of last result

### ISSUE THREAD

**Issue by althonos** [NerdyPepper/eva#23]
Hi !

`eva` is for sure a very polished piece of software. However there is one thing I think it is lacking right now (or maybe it has that already, but it is not advertised anywhere in the docs):

The Python shell has a very nifty shortcut that let's you capture the result of the last expression in the next expression to be evaluated using the `_` variable as a special case:
```python
>>> 1+1
2
>>> _ * 3
6
```

Would you be interested in implementing that ? This way I'd consider switching to `eva` as my pocket CLI calculator for good :wink:

**Comment by oppiliappan** [comment]
i have started working on this! the syntax highlighting is a little broken for now, but as of  8b49603, you can access the previous calculation with `_`. 

it is replaced by the last valid answer in case of errors. i will add more details to the readme when the feature is more polished (i should probably move this to a different branch for now).

thank you for showing interest in `eva`, stay tuned ;)

**Comment by oppiliappan** [comment]
with @pickfire's help, i have corrected syntax highlighting (to a certain extent)!

we might have to upgrade to rustyline v5.0.1 for consistent syntax highlighting (it contains major lib changes)

sorry for the delay!

**Comment by althonos** [comment]
Wonderful! :smile:

**Comment by pickfire** [comment]
@NerdyPepper I believe I am not the one who did `_`, I just did some cleanup code for that part. You should have taken the credit. :smile:  https://github.com/NerdyPepper/eva/commit/8b49603f0c6d06bcb444bd0ee14aa5c1fbc4648c
