### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by wezm** [NerdyPepper/eva#27]
Any chance of a new release with the fixes for #16 and #17 in it?

**Comment by oppiliappan** [comment]
I am planning on addressing one more issue before a new release, overflow panics.

**Comment by oppiliappan** [comment]
done! although, overflow panics ... *sigh* ... have still not been fixed. i will get back to it when i have some time!

**Comment by wezm** [comment]
Thanks for this. I can't see the new release though https://github.com/NerdyPepper/eva/releases shows the last one being from June?

**Comment by oppiliappan** [comment]
ah my bad, i have pushed the release to crates.io, but i haven't made one on GitHub yet, i'll get on it later today.

thanks wezm!
