### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by wezm** [NerdyPepper/eva#3]
This looks like a handy tool. I'd love to create and [AUR](https://aur.archlinux.org/) package for eva. It's best to build these against publish releases instead of straight from git master though. I would be great if you could tag a [release](https://help.github.com/en/articles/creating-releases).

**Comment by oppiliappan** [comment]
TIL about drafting releases!

ill get to work on this as soon as possible!

**Comment by oppiliappan** [comment]
done! i have released v0.2.1. let me know if everything is alright.

thanks a lot for showing interest in `eva` and maintaining an AUR package <3

**Comment by wezm** [comment]
Brilliant. Here's the package: https://aur.archlinux.org/packages/eva/
