### ISSUE TITLE
[Crash Report] Array out of bounds in eva::format::pprint maybe?

### ISSUE THREAD

**Issue by evanrichter** [NerdyPepper/eva#31]
`2^63`

**Comment by oppiliappan** [comment]
are you by chance, using the version on crates.io (that is pretty outdated), ill make a new release soon, i have got too many things on my hands right now.

the newest release would give you the right output (but it would still crash on large multiplications):
```
> 2^63
9,223,372,036,854,775,808.0
```

**Comment by evanrichter** [comment]
yep that was the problem. will use version from github for now :)
