### ISSUE TITLE
Publish git tags for each release?

### ISSUE THREAD

**Issue by Ma27** [NerdyPepper/eva#32]
Would it be possible to publish a git tag for each release here? This would be way more convenient when creating packages for a distro when using the source tarball from github :)

**Comment by oppiliappan** [comment]
sorry for the delay! i'll tag those releases as soon as possible!

**Comment by oppiliappan** [comment]
I have published all tags upto v0.2.7, please do take a look and let me know what you think!

you can contact me here:
nerdypepper @ irc.rizon.net
nerdypepper at tuta dot io

cheers

**Comment by Ma27** [comment]
Awesome, thanks!
