### ISSUE TITLE
Precision problem with floating points numbers

### ISSUE THREAD

**Issue by snpefk** [NerdyPepper/eva#34]
Hi! 
Less words, more example. When I'm trying to add up `41.90 + 91.90 + 209 + 249` eva gave a `591.7999999999`, although I expected `591.80`.

**Comment by oppiliappan** [comment]
noted. `eva` uses rust's floating point arithmetic, we should definitely move over to fixed point arithmetic.

**Comment by snpefk** [comment]
I'm not a big expert in computer arithmetic, but my research (a.k.a browsing Wikipedia) [suggest](https://en.wikipedia.org/wiki/Fixed-point_arithmetic#Software_application_examples) to look at "Arbitrary-precision arithmetic" since `bc` use similar approach.

[rug](https://docs.rs/rug/1.6.0/rug/) seems like a nice choice. It's implement `Integer`, `Rational` and `Float` and  configurable (you can turn off `Complex` numbers). The only drawback I found was the dependence on GNU libraries.

**Comment by pickfire** [comment]
I recently just noticed this issue, isn't num solving this? I think it's `num_rational` that provides arbitrary precision.

**Comment by oppiliappan** [comment]
@pickfire I am afraid I never got around to actually implementing it (I imported the `num` crate and completely forgot about it soon after)

**Comment by pickfire** [comment]
@NerdyPepper Heh, you could make this a hacktoberfest issue and hope someone solve it.

**Comment by JensGrabner** [comment]
In Excel, i have these 591.800000000000068. Relative failure of 1.15E-16. Welcome in the real world ;-)

**Comment by TheTechRobo** [comment]
Running `cargo r` on the master branch works fine for me:

![image](https://user-images.githubusercontent.com/52163910/193434762-a18cbcfd-25a0-4cf8-90c4-91a5bff0dcba.png)

**Comment by pickfire** [comment]
The display is fixed in master branch, but still it doesn't support numbers larger than f64, I guess this can be closed for now.
