### ISSUE TITLE
sin/cos functions take parameter as Angle not Radian

### ISSUE THREAD

**Issue by jesseky** [NerdyPepper/eva#38]
This way looks a little weird, `sin(pi/2)` should return `1.0` instead of `0.0274121335`, maybe you can consider supporting both radian and angle, such as `sin(90deg)` or `sin(90°)` return `1.0`, and `sin(pi/2)` or `sin(1.5707963268)` return `1.0`

a little suggestion.

Great work, thank you!

**Comment by oppiliappan** [comment]
Hiya,  

`eva` has `deg` and `rad` functions for conversions between degree and radians, so you would have to do `sin(deg(pi/2))` to get `1.0`.

If you don't like this however, you can start `eva` in radian mode, with `eva -r`, that switches all trigonometric functions to take input in radian, `sin(pi/2)` would return `1.0` then :)
