### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by pickfire** [NerdyPepper/eva#46]
I believe it's been a year since we last release. We probably want to do a release.

**Comment by alerque** [comment]
Yes. Please.

**Comment by alerque** [comment]
Besides the new features not included in any releases there are a couple specific issues with the last release that make it problematic to package:

1. The lock file is out of sync and cannot be built with `--locked`.
2. The test suite does not pass on current Rust compilers.

**Comment by oppiliappan** [comment]
Sorry for the delay, lemme get on it this weekend.

**Comment by pickfire** [comment]
I was thinking of doing a release when I am free myself since I think I got the permission now (I think) but still busy, luckily @nerdypepper is back.

**Comment by pickfire** [comment]
I will be doing a release soon, but I need to do some cleanup first. Maybe also safer to do a release candidate first.

**Comment by pickfire** [comment]
0.3 is now released https://crates.io/crates/eva/0.3.0

**Comment by alerque** [comment]
Please don't re-tag the repository like that! You mess up distro packaging when you do that. There was a 0.3.0 tag on this repo back in early April and that is already distributed in Arch Linux (and possibly others). Now there is a new tag 7 hours old with new content also claiming to be 0.3.0.

**Comment by pickfire** [comment]
Sorry, I thought the v0.3.0 tag was a mistake so I retag it.

**Comment by jcgruenhage** [comment]
> Arch Linux (and possibly others)

https://github.com/NixOS/nixpkgs/pull/197003, https://github.com/void-linux/void-packages/pull/40280 and https://github.com/repology/repology-rules/issues/649 are all related to re-tagging here. Alpine also got caught in this, kinda, although they haven't updated eva yet, they just also ship the "old" 0.3.0 from back in April.

Even if you think a version was a mistake, please, please, please, don't do this. Relevant section of the semantic version spec:

> Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.

Source: https://semver.org/#spec-item-3

**Comment by chenrui333** [comment]
Following the discussions in here, can we do a new release like 0.3.1 so that it would effectively solve the downstream re-tagging issue. Thanks! cc @pickfire @nerdypepper

**Comment by pickfire** [comment]
@chenrui333 I can do it, but the people from arch, nix and void have already solved the issue by making it a subsequent patch, I would like to avoid double work for those maintainers if possible.

**Comment by alerque** [comment]
As one of the people needing to re-fix this after a bump I think doing a new release would be in order. Having two completely different versions out there with the same label can potentially cause lots of problems for users and wasted time chasing differences. Bumping a minor release to back out our hacks for the version number is pretty routine. New packagers or end users chasing down differences in things labeled the same is not routine.

**Comment by chenrui333** [comment]
> @chenrui333 I can do it, but the people from arch, nix and void have already solved the issue by making it a subsequent patch, I would like to avoid double work for those maintainers if possible.

Sorting out build/release issue is one thing, clearing out the release version confusion is another separate thing. I think releasing a new version is a trivial but important rolling forward strategy to clearing out the version confusion.

**Comment by pickfire** [comment]
I deployed a new version, 0.3.1. https://github.com/nerdypepper/eva/commit/ff3db9777215c5f7fc3700be95ff9c3c106a1b9e

**Comment by alerque** [comment]
Great. Packaging 0.3.1 went smoothly with all hackery removed (lockfile patch & version-rerelease).

**Comment by chenrui333** [comment]
Thanks @pickfire, you made our lives easier!!
