### ISSUE TITLE
Suggestion: support other number base

### ISSUE THREAD

**Issue by Hugal31** [NerdyPepper/eva#5]
I hate *bc*, but when I want to perform operation on binary or hexadecimal numbers, it is convenient.

Example (it doesn't have to be obase and ibase, it could be a command line argument)
```
> obase=16
> 42
2A
```

**Comment by oppiliappan** [comment]
love this idea! im looking into adding some more command line args (precision and such), your suggestions will make it to that list.

setting up ibase would mean changing the entire lexing logic, so this will probably take some time to implement.

ill keep you posted!

**Comment by oppiliappan** [comment]
this is has been added to eva v0.2.4! i will test it out a bit more and publish a release, until then, this is the progress:
 - new arg `--base` to set the output base. input base requires a complete rework of parsing logic, maybe sometime later :^|

to try out eva v0.2.4:
```
$ git clone https://github.com/NerdyPepper/eva
$ cargo install --force --path ./eva/
```
