### ISSUE TITLE
--fix appears to truncate versus round

### ISSUE THREAD

**Issue by wezm** [NerdyPepper/eva#58]
```
$ eva -f 1
> .1 + 4
         4.0
```

```
$ eva '.1 + 4'
         4.0999999999
```

I would have expected the result to be rounded to the specified number of decimal places (and produce 4.1) instead of truncated.

**Comment by pickfire** [comment]
Thanks for reporting this, it seemed to be a bug on the radix formatting part.

**Comment by pickfire** [comment]
Fixed for base 10 but other bases might still have this issue, not sure.

**Comment by wezm** [comment]
Awesome, thanks.
