### ISSUE TITLE
Library and no_std support

### ISSUE THREAD

**Issue by charleschege** [NerdyPepper/eva#6]
Enable usage in other areas other than the command line  like web assembly and other areas, like embedded calculators

**Comment by oppiliappan** [comment]
I have been planning on extending eva as a library, but the primary focus is interactive calculation.

`no_std` + library definitely will go into the bucket list, its really exciting from what I read!

**Comment by stevedonovan** [comment]
Even just initially as a std library would be useful, especially if there was a clean way to add custom functions.  One application could be a remote TCP prompt _into_ a running application.

**Comment by pickfire** [comment]
Nice idea, I would like to try wasm and remote tcp. Hopefully I can get this after 3.0 release, aiming for 3.1. But I am not so sure about `no_std`.
