### ISSUE TITLE
Change license to apache or MIT

### ISSUE THREAD

**Issue by charleschege** [NerdyPepper/eva#7]
Current license GPLv3 limits use in commercial applications. I recommend using Apache as this will allow the library to be used by others in their open-source and commercial applications without limitations. A calculator can be used in a wide range of applications if it's not restricted by it's license

**Comment by charleschege** [comment]
The  scientific libraries in rust can really use a boost by having a lot of crates that are compatible with each other making it easier to use rustlang libraries

**Comment by oppiliappan** [comment]
I understand. The GPL licence is kinda _restrictive_. Ill switch over to MIT.
