### ISSUE TITLE
how to easier calculate a percentage?

### ISSUE THREAD

**Issue by jackywu** [NerdyPepper/eva#79]
in order to calculate `(11433-10306)/11433` ,  I have to repeat `11433` twice. do we have easier way to do that, such as `11433 percent-on 10306`, or `percent-on(11433, 10306)`. ?

**Comment by pickfire** [comment]
I am not aware of any other alternatives that do this in an easy and discoverable way. Going to close this for now unless you think otherwise. Thanks for submitting the issue.
