### ISSUE TITLE
CTRL-C causes thread main to panic

### ISSUE THREAD

**Issue by strangelovephd** [NerdyPepper/eva#9]
Exiting continuous mode with Ctrl-C causes it to panic.

thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Io(0s { code:13, kind: PermissionDenied, message: "Permission denied" }), src/libcore/result.rs:1009:5

**Comment by oppiliappan** [comment]
This looks like `rustyline` is trying to write the history to a location to which it does not have write access, but I cannot be sure.

Could you tell me more about your setup? 
 - did you build `eva` or install it from crates.io
 - output of `which eva`
 - output of `ls -al ~/history.txt`

It is [well known](https://internals.rust-lang.org/t/add-filename-information-to-io-error/5120) that `io::Error` is slightly ambiguous when it comes to issues with creating / writing files.

**Comment by strangelovephd** [comment]
crates.io
which eva: /home/sisyphus/.cargo/bin/eva
output of ~/history.txt: No such file or directory

I can try building it from source and see if that does the same thing.  Currently using Pop!_OS.

**Comment by oppiliappan** [comment]
Ah ok, looks like `rustyline` is not creating a history file, and fails to write to it.

`touch ~/history.txt` might fix your issue. Just make sure you have `rw` permissions on the history file `chmod +rw ~/history.txt`

**Comment by strangelovephd** [comment]
I thought that was the issue, because it worked just fine installing it from source.  I created the history.txt file and have rw permissions, but it's still giving the same error.

**Comment by strangelovephd** [comment]
interestingly, after building from source and running version from crates.io, the issue seems to have disappeared and I can't replicate it.  I have the ```history.txt``` file in my home directory, and an additional ```history.txt``` file in

**Comment by oppiliappan** [comment]
Same here, I can't replicate the issue. I will dig deeper when I have some time.

Since none of the other users have reported this issue, I'll close this for now.
